# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

resources:
  repositories:
  - repository: self
    checkoutOptions:
      submodules: true

jobs:
 - job: Windows_64_Bit
   pool:
     vmImage: 'windows-latest'
   steps:
    - powershell: |
        mkdir build
        $ProgressPreference = 'SilentlyContinue'
        wget "https://download.java.net/java/ga/jdk11/openjdk-11_windows-x64_bin.zip" -O "build\jdk.zip"
      displayName: 'Download JDK'
    - task: JavaToolInstaller@0
      inputs:
        jdkSourceOption: localDirectory
        jdkFile: 'build/jdk.zip'
        jdkDestinationDirectory: 'build/jdkinst'
        jdkArchitectureOption: x64
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        publishJUnitResults: false
        # testResultsFiles: '**/TEST-*.xml'
        tasks: 'build --stacktrace --info -x test'
        # checkStyleRunAnalysis: true
        # pmdRunAnalysis: true
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: 'build/reports/jacoco/test/jacocoTestReport.xml'
        reportDirectory: 'build/reports/jacoco/test/html'
